### ISSUE TITLE
Fails conformU

### ISSUE THREAD

**Issue by profhuster** [IanCassTwo/rpicam-ascom-alpaca#3]
I installed on a Rpi 3B with a fresh bullseye lite install (2023-12-05-raspios-bullseye-armhf-lite.img.xz). My only note is to run `python setup.py` before `python app.py`. It responds:
```[3:46:00.077700821] [17970]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
[3:46:00.125957070] [17971]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media2 and ISP device /dev/media0
[3:46:00.126073006] [17971]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
[3:46:00.129377717] [17970]  INFO Camera camera_manager.cpp:297 libcamera v0.0.5+83-bde9b04f
[3:46:00.176363925] [17974]  INFO RPI vc4.cpp:437 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media2 and ISP device /dev/media0
[3:46:00.176541527] [17974]  INFO RPI pipeline_base.cpp:1101 Using configuration file '/usr/share/libcamera/pipeline/rpi/vc4/rpi_apps.yaml'
```
Then a lot of INFO logs, then finally
```
2024-02-12T22:54:37.733 INFO ==STARTUP== Serving on 10.0.0.67:5555. Time stamps are UTC.
```
I downloaded and installed [Conform Universal - 2.1.0] and ran it. I connected to the IP and Port: 5555. conformu did not find my device by discovery, so I manually entered the IP & Port.

The Device Setup just referred my to `config.toml`. Check Protocol found and probed my camera and threw a lot of errors. 
On the RPi it started 
```
2024-02-12T23:20:11.700 INFO Camera configuration has been adjusted!
[4:11:34.372632242] [17970]  INFO Camera camera.cpp:1033 configuring streams: (0) 640x480-BGR888 (1) 4056x3040-SBGGR12
[4:11:34.373682598] [17974]  INFO RPI vc4.cpp:565 Sensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 4056x3040-SBGGR12_1X12 - Selected unicam format: 4056x3040-BG12
2024-02-12T23:20:11.706 INFO Configuration successful!
2024-02-12T23:20:12.373 INFO Camera started
2024-02-12T23:20:12.587 ERROR Device number 99999 does not exist. Maximum device number is 0.
```
Then many ERROR's. Finally 
```
2024-02-12T23:20:27.916 ERROR Request has bad Alpaca ClientTransactionID value qweqwe
2024-02-12T23:20:27.950 INFO Camera stopped
2024-02-12T23:20:27.967 INFO Camera started
2024-02-12T23:20:31.053 ERROR InvalidValueException: Duration asduio6fghZZ not a valid number.
```
On the ConformU It logged
```
18:20:11.616 Connecting to device: 10.0.0.67:5555 through URL: http://10.0.0.67:5555 
18:20:11.616  
18:20:11.616 OK messages are suppressed, they can be enabled through the Alpaca and COM settings page. 
18:20:11.616  
18:20:11.616 Connecting to device... 
18:20:12.498 Successfully connected to device, testing... 
18:20:17.682 PUT CoolerOn                  ISSUE  Parameter CoolerOn (Bad value) - Expected HTTP status: 400 (BadRequest) but received status: 200 (OK).
18:20:17.682 PUT CoolerOn                  ISSUE    Response: {"ServerTransactionID":111,"ClientTransactionID":67890,"ErrorNumber":1024,"ErrorMessage":"Property or method not implemented."}
```
A lot more. One ERROR:
```
18:20:42.106                               ERROR  System.TimeoutException: The "StartExposure" operation exceeded the timeout of 10 seconds specified for this operation.
   at ConformU.AlpacaProtocolTestManager.WaitWhile(String actionName, Func`1 waitFunction, Int32 pollInterval, Int32 timeoutSeconds, Func`1 statusString) in J:\ConformU\ConformU\AlpacaProtocolTestManager.cs:line 2641
   at ConformU.AlpacaProtocolTestManager.<>c__DisplayClass40_0.<TestCamera>b__0() in J:\ConformU\ConformU\AlpacaProtocolTestManager.cs:line 571
   at ConformU.AlpacaProtocolTestManager.PutTwoParameters(String method, String parameterName1, String parameterValue1, String parameterName2, String parameterValue2, Action waitForCompletion, Boolean testParameter1BadValue, Boolean testParameter2BadValue) in J:\ConformU\ConformU\AlpacaProtocolTestManager.cs:line 1686
   at ConformU.AlpacaProtocolTestManager.TestCamera() in J:\ConformU\ConformU\AlpacaProtocolTestManager.cs:line 569
   at ConformU.AlpacaProtocolTestManager.TestAlpacaProtocol() in J:\ConformU\ConformU\AlpacaProtocolTestManager.cs:line 243
```

Any suggestions of what is wrong and how t proceed?

Thank you.

**Comment by IanCassTwo** [comment]
I've never tried to connect ConformU directly. Try this instead:- 

Back on your Windows PC, run the ASCOM Diagnostics, then "Choose and Connect to a Device", Select "Camera" from the dropdown, then use the Alpaca menu to turn on Alpaca device discovery. It should then find the Raspberry PI camera and offer to install it for you. From that point onwards, you can just select it in NINA or PHD2 like you would any other ASCOM driver.

**Comment by profhuster** [comment]
I tried without success. Here are my notes:
- Back to Connection Tester => Select Device Type
  - Camera => `RpiCam4 (ASCOM AlpacaDynamic1.Camera => rpica4.local:5555/api/Camera0) - Unknown`
  - [OK]
  - x - Connect to retreive properties, [Properties]
```
Create Creating Device
Connected Setting Connected = True
SetupError Error trying to contact Alpaca device. Responce status: Error, Status code: 0, Error message: 'The operation has timed out'
Dispose Disposing of device
Dispose Completed disposal of device
```
- Tried again to configure camera in "Driver Setup Dialog Error"
```
"ASCOM:AlpacaDynamic1.Camera" threw an exception when called
This means that the setup dialogue would not start properly.

COMException: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
```

**Comment by profhuster** [comment]
BTW, I tried both normal and 32-bit modes.

**Comment by IanCassTwo** [comment]
I think those errors from ConformU are expected. ConformU will send all kinds of garbage and expect it to be rejected, however it will still be logged if your log level is too low. Change it to INFO in config.toml. I think your actual problem is not related to those errors
